#!/bin/bash

cd "$HOME"
# update base installations
sudo pacman -Syu

# install pkglist
sudo pacman -S --needed - < pkglist

# install yay 
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd "$HOME"

# install nodejs
curl -sL install-node.now.sh/lts | sudo bash

echo "Init submodules"
yadm submodule update --recursive --init
